// <auto-generated />
using System;
using BookQuoteApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookQuoteApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830225050_AddCreatedAtToModels")]
    partial class AddCreatedAtToModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("BookQuoteApi.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 94, DateTimeKind.Utc).AddTicks(5858),
                            PublicationDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "George Orwell",
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 94, DateTimeKind.Utc).AddTicks(7403),
                            PublicationDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "Jane Austen",
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 94, DateTimeKind.Utc).AddTicks(7415),
                            PublicationDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        });
                });

            modelBuilder.Entity("BookQuoteApi.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(5902),
                            QuoteText = "It is never too late to become what you might have been.",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6818),
                            QuoteText = "The only way out is through.",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6824),
                            QuoteText = "Not all those who wander are lost.",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6826),
                            QuoteText = "The future depends on what you do today.",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6829),
                            QuoteText = "Success is the sum of small efforts, repeated day in and day out.",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6831),
                            QuoteText = "Whatever you are, be a good one.",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6833),
                            QuoteText = "There is no charm equal to tenderness of heart.",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("34343434-3434-3434-3434-343434343434"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6836),
                            QuoteText = "Every moment is a fresh beginning.",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("56565656-5656-5656-5656-565656565656"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6838),
                            QuoteText = "What we think, we become.",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("78787878-7878-7878-7878-787878787878"),
                            CreatedAt = new DateTime(2026, 8, 30, 22, 50, 50, 95, DateTimeKind.Utc).AddTicks(6840),
                            QuoteText = "Happiness depends upon ourselves.",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("BookQuoteApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "john.doe@example.com",
                            PasswordHash = "$2a$11$kdkkb02uH1l3mEwE9XJade17qR9qnrAwAJgTqN5gm.HbunF.954P2",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "mary_smith@example.com",
                            PasswordHash = "$2a$11$dnE9bXLxEyQA7wrLWc7mveCpwtb3NGQC.xmnIYPDC1bL3kq4b90X6",
                            Username = "Mary_smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
